### PR TITLE
Merge multidev env to dev after feature branch merged to master

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Add a merge-pantheon-multidev script to merge the tested multidev into the dev environment after any branch is merged to 'master' (after the master branch tests pass). For testing, though, we will merge all test environments back to dev.

### CODE REVIEW

**Comment by stevector** [comment]
@greg-1-anderson, is the idea here that when merging to master, a mutlidev already exists where the some have been run? If so, the merge could be as simple as `terminus site merge-to-dev`, right?

**Comment by greg-1-anderson** [comment]
stevector I don't think that would always work due to potential merge conflicts in the `vendor` directory.

**Comment by greg-1-anderson** [comment]
Merging to test deployment via this technique.

Need to be a little creative to test `terminus site merge-to-dev` by making two PRs off of the same commit that make changes that do not conflict with each other, but cause conflicts in `vendor`. Or read the Terminus source code and see if it does anything special, or just runs `git merge`. The later (with all of the protection of `git`) is probably what's wanted most of the time.

**Comment by greg-1-anderson** [comment]
I don't think that `terminus site merge-to-dev` will work (`terminus site merge-to-dev` just ends up running `git merge`), but perhaps `git merge -X theirs` would be more efficient (and less "magical") than the current implementation of replacing one tree with another.

**Pull request merged**
