### PR TITLE
[OTTO-76] Convert from drupal-composer/drupal-scaffold to drupal/core-composer-scaffold

### PR DESCRIPTION
**Pull request by greg-1-anderson**

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I thought I would try setting '[skip_permissions_hardening](https://github.com/pantheon-systems/drupal-integrations/blob/master/assets/settings.pantheon.php#L207)' to make scaffolding work better, but this results in warnings after installation completes:

Screen Shot 2020-01-29 at 4 32 02 PM

**Comment by greg-1-anderson** [comment]
I removed the part that disabled permissions hardening to avoid the warning shown above.

**Comment by ChristopherMatthews** [comment]
@greg-1-anderson, when you're able, can you detail how to make the switch from `"drupal-composer/drupal-scaffold": "^2.0.1"` to `"drupal/core-composer-scaffold": "^8.8.1"`? Or, is it as simple as replacing drupal-composer/drupal-scaffold with drupal/core-composer-scaffold in composer.json?

**Comment by alisonjo315** [comment]
Hi!  Just to follow-up on @ChristopherMatthews's question:

Did you use these d.o instructions for converting, plus adding the pantheon integration piece, or do you have other steps?
https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#s-migrating-composer-scaffold

**Comment by alisonjo315** [comment]
NM -- I forgot we discussed in Slack ....all of... 12 days ago... omg :broken-brain-slack-emoji:

**Info from that convo, for others (including Future Me):**

Good place to start:
https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#s-migrating-composer-scaffold

Then, Pantheon-specific stuff in composer.json:
* Add pantheon-systems/drupal-integrations
* In "extras/drupal-scaffold", remove everything that's there and add `"allowed-packages": [ "pantheon-systems/drupal-integrations" ]` and the web-root

Then, remove composer.lock and vendor/ and run `composer update`.

**Pull request merged**
