### PR TITLE
Update composer.json for Composer 2 compatibility.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
This is a start. This composer.json does update, but still contains the following warnings:
```
Class Symfony\Cmf\Component\Routing\Tests\Mapper\FieldMapEnhancerTest located in ./vendor/symfony-cmf/routing/Tests/Enhancer/FieldMapEnhancerTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Cmf\Component\Routing\PagedRouteCollectionTest located in ./vendor/symfony-cmf/routing/Tests/Routing/PagedRouteCollectionTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Symfony\Cmf\Component\Routing\LazyRouteCollectionTest located in ./vendor/symfony-cmf/routing/Tests/Routing/LazyRouteCollectionTest.php does not comply with psr-4 autoloading standard. Skipping.
Class EasyRdf_Serialiser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Serialiser/JsonLd_real.php does not comply with psr-0 autoloading standard. Skipping.
Class EasyRdf_Parser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/JsonLdImplementation.php does not comply with psr-0 autoloading standard. Skipping.
Class Drush\CommandFiles\Core\BrowseCommands located in ./vendor/drush/drush/lib/Drush/CommandFiles/core/browseCommands.php does not comply with psr-0 autoloading standard. Skipping.
```
Hm, I am wondering if we will need to go up to Drupal 9 to clear up the Symfony problems. Trying that next.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Sure enough, upgrading to Drupal 9 cleared up the Symfony warnings. These are only test files, though, and therefore these warnings are innocuous. Leaving this project at Drupal 8 for now, since this is, after all, "example-drops-**8**-composer".

I dropped rvtraveller/qs-composer-installer. We have https://github.com/rvtraveller/qs-composer-installer/pull/3, but at first blush, only the author seems to be using this plugin. It is possible that others might be using qs scripts provided by the author, or scripts not published on Packagist. Impact of dropping this is low, I think.

I also dropped zaporylie/composer-drupal-optimizations. This is unnecessary with Composer 2, and only provides minimal improvements with Composer 1. Dropping this dependency will simplify our move to Composer 2.

At this point, the only thing we need before we could merge here is https://github.com/cweagans/composer-patches/issues/332. Once we have that, we can bump our cweagans/composer-patches version constraint to ^1.7 (it will probably be).

**Comment by greg-1-anderson** [comment]
@sugaroverflow FYI

**Comment by greg-1-anderson** [comment]
Works. Recommend merging and tagging.

**Review by sugaroverflow — APPROVED** [review]
The process and updates make sense to me 👍 ready for merge

**Pull request merged**
