### PR TITLE
Gitlab CI Implementation

### PR DESCRIPTION
**Pull request by derimagia**
Some comments about this on #19. Want some feedback on it.

1. Added gitlab-ci implementation /  .gitlab-ci.yml
2. Uses Environments on Circle CI
3. Added Gitlab Comments similar to Github Comments, but with Environments I'm second guessing if this was needed.
4. Changed run-behat to not need to be in a specific directory
5. Added TERMINUS_LABEL variable for commit messages
6. Defaulted variables in scripts to reasonable defaults, checking both variables for CircleCI and the "Generic" Version of the variables for Gitlab CI

This does not have work with Robo in it 

One decision I probably will make for this is to not have commit specific environments but change it to branch-specific environments. The script that exists doesn't delete old commit-branches, I noticed. It was only deleting the multi-dev so there were a lot of branches left on Pantheon.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Thanks for the improvements!

Since the scripts themselves don't really have much Gitlab-specific branching (just comment posting), converting to Robo or some other higher-level scripting language is not necessary for this PR (but still a nice to have, as a separate independent effort).

Regarding feature branches vs build-number branches, the problem with the former is that your tests will conflict and fail if multiple commits are made to a branch before the running tests can complete. Unless you add some sort of build semaphore on CircleCI, the later build will ruin the earlier build. Perhaps this is a limitation that folks would be willing to live with. Using a single feature branch also has the advantage of having a more stable test environment, e.g. if using the test environment to showcase a feature to stakeholders through multiple revisions.

One thought I had in this area was to vary the multidev environment name depending on the naming conventions of the PR branch.  If the branch starts with 'feature-', then the remaining portion of the branch name would be used in the environment name.  e.g. the `feature-foo` branch would create a multidev environment `ci-foo` (or something else not eligible for deletion by delete-old-multidevs -- feature branches would clean up on merge). If the branch did not start with `feature`, then the build number would be used as usual. This would put the behavior of the environment creation in the hands of the user.

Regarding branch cleanup, yes, the script should definitely delete the branch when cleaning up old multidevs.  I just need to add `--remove-branch` to the Terminus command when deleting the multidev. I'll do that momentarily.

**Comment by derimagia** [comment]
Another option would be to have 1 multi-dev per feature branch and then every commit in the branch would get it's own environment with the test running on that one. The branch multi-dev can be updated with code like usual, but that was you have both.

To deal with a semaphore could also use a file lock could be used in the files directory of the site. I do like the idea of options, though, even if it was just a variable

**Comment by derimagia** [comment]
How did you want to do tests for the Gitlab section? Have any thoughts/interests? Maybe just sync the repo to a gitlab repo with a different terminus_env?

**Comment by greg-1-anderson** [comment]
If you want to maintain the gitlab repo, that would be appreciated. Otherwise, I am satisfied to leave the gitlab file as an untested example.

**Comment by greg-1-anderson** [comment]
Did some refactoring of the circle.yml file. Earlier I made some passing effort at also  updating the gitlab CI, but it is probably not working now.

**Comment by derimagia** [comment]
Just as an update - still plan on doing this. @rvtraveller was taking a look and I believe there's just a few tweaks to do

**Pull request merged**
