### PR TITLE
Improve style of 'visit site' link posted by CI bot.

### PR DESCRIPTION
**Pull request by greg-1-anderson**

### CODE REVIEW

**Comment by derimagia** [comment]
I mention in another post that I'm posting a lot of this to gitlab so I went through a lot of the code for it. Minor but since this pull request already exists, is there a reason why the comment is exported?

**Comment by greg-1-anderson** [comment]
Do you mean why `export comment=` instead of just `comment=`?  No reason, it was just there like that. Don't know why I didn't bother to take it out. Might as well do that.

**Comment by greg-1-anderson** [comment]
... and now the tests fail until I have a tag for 8.2.4 in drops-8.  Or pin to 8.2.3 in composer.json. Sigh.

**Comment by derimagia** [comment]
Yeah... I got the same thing on my work I'm doing.

**Comment by greg-1-anderson** [comment]
Limitation of the way I'm using drupal-scaffold.  We take the best tag from drupal/core, and expect that drops-8 will have the same tag.  I'll do the update of drops-8 shortly.

**Comment by greg-1-anderson** [comment]
@derimagia Where are you doing your GitLab work?  If it's not too different, it might make sense to integrate.  Maybe after switching the scripts from Bash to Robo, so that the repository-specific parts can be factored out.

**Comment by derimagia** [comment]
Right now at gitlab private repo, but I was planning to move it over to a pull request on github

Robo sounds like a great idea, once I test what I have further I'll take a look at it

**Pull request merged**
